version: "2"
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on: 
      - web
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"